### ISSUE TITLE
Помилка на Windows

### ISSUE THREAD

**Issue by cirin0** [KR1470R/plagiator-py#1]
При спробі виконати рядок: 
`pip install -r requrements.txt`

PowerShell видає помилку:

`ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requrements.txt'`

Відповідно запуск main файлу не можливе. Коли я намагаюся це зробити то PowerShell повертає:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\*****\Desktop\plagiator-py\main.py", line 3, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```

Можливо я щось роблю неправильно.

**Comment by KR1470R** [comment]
my bad, in the instructions i've got a mistake in the ` pip install -r requrements.txt`, it should be ` pip install -r requirements.txt`
